### ISSUE TITLE
Window path error

### ISSUE THREAD

**Issue by vinyvince** [codewings/Houdini-Custom-Viewport-Shader#1]
Hey the shader look neat and sexy, never seen a custom viewport shader before made by anyone, congratulation! thats really cool!  :) 

On windows, your hardcode path relative for an mac Os env, sadly is not friendly with a window env. 

me: Error loading function me 
opalias: 'mlops::export_image::1.0' is not a known operator.
opalias: 'mlops::transform_image::1.0' is not a known operator.
export OPENIMAGEIO_IMAGECACHE_OPTIONS=unassociatedalpha=1
C:/Users/vincent/Documents/Library/Preferences/houdini/19.5/glsl/anime/ogl3_gbfv.prog not exist

**Comment by codewings** [comment]
Thanks for letting me know about the issue. I have changed the prog file path and you didn’t have to copy the 'glsl' directory. 
Additionally，if there are errors with glsl_shader_validator, it could be due to a lack of C++ compiler installation. it might be better to use HDK to extend HOM to implement this operator.
